services:
  notebook:
      platform: linux/amd64
      build: 
        context: .
        dockerfile: docker/notebook/Dockerfile
      image: spark-notebook:latest
      container_name: spark-notebook
      command: start-notebook.sh --NotebookApp.token=''
      volumes:
       - ./notebook/:/notebook/
      environment:
        - SPARK_COMPAT_VERSION=${SPARK_COMPAT_VERSION}
        - SCALA_COMPAT_VERSION=${SCALA_COMPAT_VERSION}
        - CATBOOST_SPARK_VERSION=${CATBOOST_SPARK_VERSION}
        - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
        - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
        - CLICKHOUSE_USER=${CLICKHOUSE_USER}
        - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      ports:
        - 8888:8888
      # networks:
      #   - cp-network

