services:
  notebook:
      platform: linux/amd64
      build: 
        context: .
        dockerfile: docker/notebook/Dockerfile
      image: spark-notebook:latest
      container_name: spark-notebook
      command: start-notebook.sh --NotebookApp.token=''
      volumes:
       - ./notebook/:/notebook/
      environment:
        - SPARK_COMPAT_VERSION=${SPARK_COMPAT_VERSION}
        - SCALA_COMPAT_VERSION=${SCALA_COMPAT_VERSION}
        - CATBOOST_SPARK_VERSION=${CATBOOST_SPARK_VERSION}
        - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
        - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
        - CLICKHOUSE_USER=${CLICKHOUSE_USER}
        - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      ports:
        - 8888:8888
      depends_on:
        db:
          condition: service_healthy
          restart: true
      networks:
        - cp-network
  db:
    image: clickhouse:latest
    platform: linux/amd64
    container_name: pyspark-clickhouse 
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse/
      - ./clickhouse/logs:/var/log/clickhouse-server/
      - ./clickhouse/config/:/etc/clickhouse-server/config/
      - ./clickhouse/users/:/etc/clickhouse-server/users.d/
      - ./clickhouse/csv:/var/lib/csv/
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    healthcheck:
      test: wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - cp-network

networks:
  cp-network:
    name: cp-network
